### ISSUE TITLE
run_inerf.py   unrecognized arguments

### ISSUE THREAD

**Issue by hundun0322** [silvery107/fast-inerf#2]
When I run the command：python scripts/run_inerf.py --config configs/inerf/PROPS.txt --posecnn_pose_init --mask_region，
it shows run_inerf.py: error: unrecognized arguments:  --config configs/inerf/PROPS.txt --posecnn_pose_init --mask_region.

**Comment by silvery107** [comment]
Hi, I just pushed the fix. Try pull it and rerun:

```
python scripts/run_inerf.py --config configs/inerf/PROPS.txt --posecnn_init_pose --mask_region
```

**Comment by hundun0322** [comment]
> Hi, I just pushed the fix. Try pull it and rerun:
> 
> ```
> python scripts/run_inerf.py --config configs/inerf/PROPS.txt --posecnn_init_pose --mask_region
> ```

Thank you very much for your help.

**Comment by silvery107** [comment]
Closed as completed.
